#!/bin/sh

# generate index.html and the static site.

set -e

while getopts "o:s:h" arg
do
	case "${arg}" in
		"o")
			export OUT="${OPTARG}"
		;;
		"s")
			export SRC="${OPTARG}"
		;;
		"h")
			echo "${0##*/}: manual."
			exit 0
		;;
	esac
done

if [ -d "${OUT:-site}" ]
then
	printf "<!-- Auto generated by %s -->" "${0##*/}" > "${OUT:-site}/index.html"
	if [ -d "${SRC:-source}" ]
	then
		for d in "${SRC:-source}"/*
		do
			if [ -d "${d}" ]
			then
				(
					cd "${d}"
					if [ -f "ctx.sh" ]
					then
						unset TITLE TEXT FILE
						. ./"ctx.sh"
						echo "${d##*/}: ${TITLE}"
					fi
				)
			fi
		done
	fi
else
	echo "${0##*/}: Output directory doesn't exists."
	exit 1
fi
