#!/bin/sh

# generate index.html and the static site.

set -e

while getopts "o:s:h" arg
do
	"o")
		export OUT="${OPTARG}"
	;;
	"s")
		export SRC="${OPTARG}"
	;;
	"h")
		echo "${0##*/}: manual."
		exit 1
	;;
done

printf "<!-- Auto generated by %s -->" "${0##*/} -->" > "${OUT:-.}/index.html"
